[build]
  command = "go build -o ./bin/app ."
  publish = "public"
  functions = "functions"

[build.environment]
  GO_IMPORT_PATH = "github.com/github/testdatabot"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[functions]
  directory = "functions"
  node_bundler = "esbuild"